### ISSUE TITLE
Smaller screen problem

### ISSUE THREAD

**Issue by bbrtj** [nicomen/shinyperl#2]
![image](https://user-images.githubusercontent.com/44323413/121605401-a0db8b80-ca4c-11eb-8816-a6ee7ecfa959.png)

I've got 15.6", 1366x768 laptop screen. Bottom text gets in the way of longer snippets

**Comment by nicomen** [comment]
Thanks, I will try to improve this!

**Comment by nicomen** [comment]
I hope it looks better now on any screen, could you check?

**Comment by bbrtj** [comment]
Yes, it looks much better now. Although there are now some unnecessary sliders, even for small examples. See the screenshot:

![image](https://user-images.githubusercontent.com/44323413/121769876-52baab00-cb66-11eb-950e-978829e18920.png)

**Comment by nicomen** [comment]
Hopefully the scrollbar is gone now too

**Comment by bbrtj** [comment]
Yes, its gone. There's one more related problem though, I had to increase the size of an example in HTML to produce it, but it will work the same with current examples but when the window is resized to be shorter. The scrollbar is never visible, so what we get is what you can see on the screenshot below - there's no way to scroll it down.

I would suggest replacing `body` style `overflow: hidden` with `overflow-x: hidden`. It fixes the issue for me.

![image](https://user-images.githubusercontent.com/44323413/121777424-41879380-cb92-11eb-98f2-ff5f4a7fb099.png)

**Comment by nicomen** [comment]
Of course, you are right, thanks.

**Comment by bbrtj** [comment]
Perfect, closing the issue.
