### ISSUE TITLE
Moo example does not compile

### ISSUE THREAD

**Issue by bbrtj** [nicomen/shinyperl#3]
What I got from the website:
```
package Point {
	use Moo;

	has 'x' => isa => sub { m{\d+} };
	has 'y' => isa => sub { m{\d+} };

	sub describe {
	  print "A point at ($x, $y)";
	}
}

Point->new(4,2)->describe; # A point at (4,2)
```

I get:
```
Global symbol "$x" requires explicit package name (did you forget to declare "my $x"?) at test.pl line 10.
Global symbol "$y" requires explicit package name (did you forget to declare "my $y"?) at test.pl line 10.
```

Additional problems with that example are:
- `has` needs `is`, croaks with `Must have an is at test.pl line 6.`
- the constructor needs a hash, so `->new(x => 4, y => 2)`
- `isa` subs doesnt seem to have `$_`, so it needs to use an argument, like `shift =~ m{\d+}`
- `m{\d+}` doesn't check if the value is a number, but instead if it contains numbers, so it needs some anchors

So to make it work for me, I came up with this (as few changes as possible, trying to keep it short):
```
package Point {
    use Moo;

    has ['x', 'y'] => (
        is => 'ro',
        isa => sub { shift =~ m{\A \d+ \z}x }
    );

    sub describe {
        my ($self) = @_;

        printf "A point at (%d, %d)",
            $self->x, $self->y;
    }
}

Point->new(x => 4, y => 2)->describe; # A point at (4,2)
```

**Comment by nicomen** [comment]
Thanks for the report and the solution. I didn't use all of it, as I wanted the explicit version to be there, but perhaps a separate "advanced" attribute definition would be nice.

**Comment by atoomic** [comment]
maybe consider using single quotes `'` for the sentence using `$x` and `$y`?
```perl
sub describe {
	  print 'A point at ($x, $y)';
	}
```

**Comment by nicomen** [comment]
Wouldn't that circumvent the point of actually interpolating the variables?

**Comment by bbrtj** [comment]
hello @nicomen 
It is much better now, but there's still a warning:
```
Use of uninitialized value $_ in pattern match (m//) at test.pl line 5.
```

That's because `isa => sub { m{\A\d+\z} }` does not operate on `$_`, so the current check does not actually check anything. You need `isa => sub { shift =~ m{\A\d+\z} }` (the `shift` is the first argument to a function, which is where the value is).

In addition to that, it struck me that the program does not actually die automatically. You'll have to write something like `isa => sub { die 'not a number' unless shift =~ m{\A\d+\z} }`, because otherwise it accepts non-numbers anyway.

At this point, I think it's better to strip off the `isa` entirely, and leave just `has 'x' => is => 'rw';` (and same for y). Maybe leave typechecks for another example with something like Type::Tiny

**Comment by nicomen** [comment]
Thanks for taking all the time with the feedback. I think you are right. The intention was to show how easy one could do type checking, but I was a bit fast and it's not _that_  easy (although fairly), but like you say it might be as good to just use one of the Type modules in that case.

**Comment by nicomen** [comment]
(But, perhaps Moo should indeed set $_ and use the return value of the sub to decide wether to throw an error :-)

**Comment by bbrtj** [comment]
Maybe it should! But sadly, I'm sure it will not be possible at this stage. If those subs were not meant to return anything, making Moo check their return value will surely break some code. But maybe the `$_` part is doable.

As for the Moo example, it looks like its good now. I'll close the issue.
