### ISSUE TITLE
Not obvious how to advance the slides

### ISSUE THREAD

**Issue by oalders** [nicomen/shinyperl#4]
This looks great! It's just not obvious to me how to advance to the next slide. I do see `<div id="slideshow" onclick="next_slide">`, but clicking around doesn't seem to make anything happen any faster for me. :)

**Comment by nicomen** [comment]
Thanks, I just pushed out the minimal thing I could do as all of these was setup betwen talks on the last day of the conference.

I'm refactoring the whole thing and trying to find a suitable slideshow/carousel/slider that does not requires downloading the entire npm repo, requires this (or last) week's only true javascript framework, nor take some megabytes to download for visitors. 

Feel free to give me a tip of clever ones!

**Comment by nicomen** [comment]
Could you check if you think it's slightly more obvious now?

**Comment by oalders** [comment]
@kevcenteno do you have any suggestions?

**Comment by oalders** [comment]
Checked on mobile. Much clearer!
